/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframehopital;

import database.DatabaseConnection;
import hospital.Login;

/**
 *
 * @author pc
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lTittle = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        tLogin = new javax.swing.JButton();
        tPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(49, 186, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTittle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lTittle.setForeground(new java.awt.Color(255, 0, 51));
        lTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTittle.setText("Phòng khám bệnh đa khoa 73 Quang Trung");
        jPanel2.add(lTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 43, 510, 46));

        lUser.setBackground(new java.awt.Color(102, 255, 102));
        lUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lUser.setText("TÊN ĐĂNG NHẬP");
        jPanel2.add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 130, 40));

        lPassword.setBackground(new java.awt.Color(102, 255, 0));
        lPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lPassword.setText("MẬT KHẨU");
        jPanel2.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 180, 130, 40));

        tUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserActionPerformed(evt);
            }
        });
        jPanel2.add(tUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, 40));

        tLogin.setBackground(new java.awt.Color(255, 0, 102));
        tLogin.setForeground(new java.awt.Color(255, 0, 0));
        tLogin.setText("LOGIN");
        tLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLoginActionPerformed(evt);
            }
        });
        jPanel2.add(tLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 120, 38));
        jPanel2.add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLoginActionPerformed
        Login login = new Login(tUser.getText(), String.valueOf(tPassword.getPassword()));
        int x = login.login();
        if (x == 1) {
            MainFrame mf = new MainFrame();
            mf.setVisible(true);
            this.setVisible(false);
        } else {
            tUser.setText("");
            tPassword.setText("");
        }
    }//GEN-LAST:event_tLoginActionPerformed

    private void tUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Handle Exception
        } catch (InstantiationException ex) {
            //Handle Exception
        } catch (IllegalAccessException ex) {
            //Handle Exception
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //Handle Exception
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lTittle;
    private javax.swing.JLabel lUser;
    private javax.swing.JButton tLogin;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
